// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBueUSfe7NVDfdk63WUvF5YvzdImbH8fJc',
    appId: '1:1054991543716:web:fa7e3b1aa3639e48cbe531',
    messagingSenderId: '1054991543716',
    projectId: 'logitrack-app-b8a97',
    authDomain: 'logitrack-app-b8a97.firebaseapp.com',
    storageBucket: 'logitrack-app-b8a97.firebasestorage.app',
    measurementId: 'G-D0RX1NW08R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiePKGtYToxZ7TPTZhRCNGpZxKRKrLV2A',
    appId: '1:1054991543716:android:af46e5880c7cd294cbe531',
    messagingSenderId: '1054991543716',
    projectId: 'logitrack-app-b8a97',
    storageBucket: 'logitrack-app-b8a97.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBueUSfe7NVDfdk63WUvF5YvzdImbH8fJc',
    appId: '1:1054991543716:web:9f8dce7a7865299acbe531',
    messagingSenderId: '1054991543716',
    projectId: 'logitrack-app-b8a97',
    authDomain: 'logitrack-app-b8a97.firebaseapp.com',
    storageBucket: 'logitrack-app-b8a97.firebasestorage.app',
    measurementId: 'G-MWEN9MZWYE',
  );
}
